services:
  mariadb:
    build: requirements/mariadb/.
    env_file: .env
    container_name: mariadb
    networks: 
    - inception
    volumes: 
    - mariadb:/var/lib/mysql
    restart: always
    expose: 
    - "3306"
  nginx:
    build: requirements/nginx/.
    env_file: .env
    container_name: nginx
    networks: 
    - inception
    ports:
      - "443:443"
    depends_on: 
    - wordpress
    volumes: 
      - wordpress:/var/www/wordpress
    restart: always
  wordpress:
    build: requirements/wordpress/.
    env_file: .env
    container_name: wordpress
    depends_on:
    - mariadb
    networks:
    - inception
    volumes: 
      - wordpress:/var/www/wordpress
    expose: 
      - "9000"
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
networks:
  inception:
    name: inception
    driver: bridge
  # drive is bridge by default 
